import Logo from "@/_components/Logo";
import Navigation from "@/_components/Navigation";
import "@/_styles/globals.css";
import { PropsWithChildren } from "react";

export const metadata = {
  title: "Septel",
  description: "Generated by Sepkey",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className="bg-accent-50 text-neutral-800 min-h-screen">
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>Copyright by Septel</footer>
      </body>
    </html>
  );
}
