import { PropsWithChildren } from "react";
import Logo from "./_components/Logo";
import Navigation from "./_components/Navigation";

export const metadata = {
  title: "Septel",
  description: "Generated by Sepkey",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <header>
        <Logo />
        <Navigation />
      </header>
      <body>
        <main>{children}</main>
        <footer>Copyright by Septel</footer>
      </body>
    </html>
  );
}
